# Generated by Django 4.2.7 on 2025-12-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_budget_user_goal_user_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
