# Generated by Django 4.2.7 on 2026-05-31 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField(verbose_name='Telegram Chat ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата привязки')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram-привязка пользователя',
                'verbose_name_plural': 'Telegram-привязки пользователей',
            },
        ),
        migrations.CreateModel(
            name='TelegramLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_codes', to='hr.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Код привязки Telegram',
                'verbose_name_plural': 'Коды привязки Telegram',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64, verbose_name='Тип события')),
                ('recipient_role', models.CharField(choices=[('employee', 'Сотрудник'), ('hr_manager', 'HR-менеджер'), ('admin', 'Администратор')], max_length=20, verbose_name='Роль получателя')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('message_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='hr.employee', verbose_name='Сотрудник')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог уведомления',
                'verbose_name_plural': 'Логи уведомлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField(verbose_name='Telegram Chat ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата привязки')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to='hr.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Telegram-привязка сотрудника',
                'verbose_name_plural': 'Telegram-привязки сотрудников',
            },
        ),
    ]
