# Generated by Django 4.2.7 on 2026-05-31 23:54

import secrets

from django.db import migrations, models


def populate_telegram_bind_codes(apps, schema_editor):
    User = apps.get_model('hr', 'User')
    used = set(
        User.objects.exclude(telegram_bind_code__isnull=True)
        .exclude(telegram_bind_code='')
        .values_list('telegram_bind_code', flat=True)
    )
    for user in User.objects.all():
        if user.telegram_bind_code:
            continue
        for _ in range(20):
            code = secrets.token_urlsafe(8)[:12].upper()
            if code not in used:
                user.telegram_bind_code = code
                user.save(update_fields=['telegram_bind_code'])
                used.add(code)
                break


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_usertelegramlink_telegramlinkcode_notificationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_bind_code',
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=16,
                null=True,
                verbose_name='Код привязки Telegram',
            ),
        ),
        migrations.RunPython(populate_telegram_bind_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='telegram_bind_code',
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=16,
                unique=True,
                verbose_name='Код привязки Telegram',
            ),
        ),
    ]
