# Generated by Django 4.2.7 on 2026-05-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_user_telegram_bind_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLinkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram Chat ID')),
                ('awaiting_code', models.BooleanField(default=True, verbose_name='Ожидает код')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сессия привязки Telegram',
                'verbose_name_plural': 'Сессии привязки Telegram',
            },
        ),
    ]
