# Generated by Django 4.2.7 on 2026-06-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_telegram_link_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Работает'), ('on_leave', 'В отпуске'), ('sick_leave', 'На больничном'), ('dismissed', 'Уволен')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
